services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin123
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock