
llm:
  url: https://api.llm.net/v1/chat/completions
  api_key: sk-lEg4SHDKlYdhR2Zo05195aF5F61a45D6AcAd71Fc4cDaDd63
  model:
    meta_llama:
      version: meta-llama/Meta-Llama-3-8B-Instruct
      temperature: 0.2

baidu:
  api_key: B8LwcewOV8ffif27jHSxiCQ3
  secret_key: 988NObqCNdMkr5Dngs78E6BranHspaBE

google:
  client_id: 473106904157-p0lf2foir7f3mdu0d2amp4b6aithud66.apps.googleusercontent.com
  client_secret: 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
  google_redirect_uri: http://127.0.0.1:8000/google_authorize

wechat:
  wechat_app_id: wxed03a467845dc9aa
  wechat_app_secret: bff0dd0cc61d6cc771fd7ffc21c7a3bf
  wechat_redirect_uri: test

paypal:
  paypal_client_id: ATlxPFgf2van_v1DIo0Beem9Js5QWdvtxsFFUOhBU5BqYdbVmQSIXvkp83NP8-ehdo72ys1IHgrVkUYc
  paypal_client_secret: EJPoIHvDwQNrgSl9QZDEQMuZJqzlb-OmfH2CNjOJ88EjQbyAH11mUL_sW9rxCrZbjKVLC4U8LGWx_Zq9
  paypal_redirect_uri: http://127.0.0.1:3000/paypal/callback
  cancel_url: http://127.0.0.1:3000/paypal/cancel_payment

postgresql:
  host: 101.42.33.129
  port: 526
  database: ichar_db
  user: root
  password: 123456
#  embedding_model:
#    model: GPT
#    modelconfig:
#      model_version: text-embedding-3-small
#      encoding_format: float
#      similarity: 0.7
#      dimensions: 512

features:
  flow_generation:
    model: llm
    modelconfig:
      model_version: meta-llama/Meta-Llama-3-8B-Instruct

  audit_report:
    model: llm
    modelconfig:
      model_version: CohereForAI/c4ai-command-r-plus

